name: Release-Flow
on:
  push:
    tags:
      - v*
jobs:
  test-job:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      get-version:
        name: Get Version Tag
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      print-version:
        name: Print Version
        run: echo ${steps.get_version.outputs.VERSION}
      checkout-version:
        name: Checkout-Version-Tag
        uses: checkout@${steps.get_version.outputs.VERSION}
