name: Release-Flow
on:
  push:
    tags:
      - v*
jobs:
    test-job:
        name: Test Job
        runs-on: ubuntu-latest
        steps:
        - name: Get Version Tag
            id: get_version
            run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        - name: Print Version
            run: echo ${steps.get_version.outputs.VERSION}
        - name: Checkout-Version-Tag
            id: checkout-version
            uses: checkout@${steps.get_version.outputs.VERSION}
