on:
  push:
    tags:
      - "v*.*.*"
name: "Template"
jobs:
  testbox:
    runs-on: ubuntu-latest
    env:
      REF_TAG: ${{ github.ref }}
    steps:
      - name: Check OS
        run: uname -r
      - name: Print Ref tag
        run: echo $(echo $REF_TAG | cut -d / -f 3)
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
