name: Release-Flow
on:
  push:
    tags:
      - v*
jobs:
  test-job:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
        - name: Get Version Tag
        id: get-version:
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        - name: Print Version
        id: print-version
        run: echo ${steps.get_version.outputs.VERSION}
