on:
  push:
    tags:
      - "v*.*.*"
name: "Template"
jobs:
  testbox:
    runs-on: ubuntu-latest
    steps:
      - name: Check OS
        run: uname -r
      - name: Check Disk Size
        run: df -h
      - name: Hello World
        run: echo Hello World
