on:
  pull_request:
    types: [opened, edited]
name: "Template for PRs"
jobs:
  testbox:
    runs-on: ubuntu-latest
    env:
      REF_TAG: ${{ github.ref }}
    steps:
      - name: Print Ref tag
        run: echo "$REF_TAG"
